DEVICE_PACKAGE_OVERLAYS += $(INTEL_PATH_DEVICE)/project-celadon/overlay

BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824

BOARD_KERNEL_CMDLINE += lpj=1600000 reboot_panic=p,w

INTEL_HWC_ALWAYS_BUILD := false

DEVICE_MANIFEST_FILE := $(INTEL_PATH_DEVICE)/cel_apl/manifest.xml

# Disable ota
TARGET_SKIP_OTA_PACKAGE := true
