[defaults]
installer = false
oemvars = true
timeout = 60000
capsule = true
reboot = continue
version = 2.1
bts = false
fastboot_min_battery_level = false
retry = 1
firmware_info = false
flash=true
clearrpmb_emmc=true
clearrpmb_ufs=true
startover=true
bootloader = true
fast_flashfiles=true
flash_dnx_os=true
blank_no_fw = false
