#version 450
#define LOCAL_SZ_X 8

layout(binding = 0) readonly buffer Input0{
    float input_buffer[];
};

layout(binding = 1) writeonly buffer Output{
    float output_buffer[];
};

layout(push_constant) uniform pushBlock {
    int total;
} p;

layout(local_size_x = LOCAL_SZ_X) in;

void main()
{
    int gid = int(gl_GlobalInvocationID.x);
    if (gid >= p.total) return;

    output_buffer[gid] = 1.0f / (1.0f + exp(-input_buffer[gid]));
}
