# This enables the wpa wireless driver
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WLAN_DEVICE := mrvl
BOARD_WPA_SUPPLICANT_PRIVATE_LIB ?= mrvl_private_lib_driver_cmd
WPA_SUPPLICANT_VERSION := VER_2_1_DEVEL

BOARD_SEPOLICY_DIRS += \
    $(INTEL_PATH_SEPOLICY)/wlan/common
