#!/usr/bin/python

# This script monitors shutdown and reboot event of guests through QEMU
# Guest shutdown/reboot will trigger entire system, the Guest CiV first
# and then Host CPU.
#
# It start QEMU with below comand:
#
# # qemu [...] -qmp unix:./qmp-sock,server
#
# and then Run the QMP shell to minitor the VM events :
#
# $ qmp-shell ./qmp-sock

from __future__ import print_function
import json
import sys
import os
import time
import subprocess
from sys import argv,exit

sys.path.append(os.path.join(os.path.dirname(__file__), 'qemu-4.2.0/python'))
from qemu import qmp

# connection timeout of two minutes
con_timeout = 2*60

def main():

    if len(argv) != 2:
        print(' <unix-socket> argument is not provided')
        exit(1)

    qemu = qmp.QEMUMonitorProtocol(argv[1])

    # Make a connection to QMP server. Break while loop only when the connection is made.
    # put a timeout 2 minutes if connection is not successful
    timeout_start = time.time()
    while True:
        try:
            qemu.connect()
            print("connected to QEMU QMP server")
            break
        except qmp.QMPConnectError:
            print('Didn\'t get QMP greeting message from QEMU QMP server')
        except qmp.QMPCapabilitiesError:
            print('Could not negotiate capabilities with QEMU QMP server')
        except qemu.error:
            print

        if time.time() >= con_timeout + timeout_start:
            print("connection timeout error")
            return


    while True:
        try:
            # Pull the VM shutdown and reboot event from QEMU QMP Server
            resp = qemu.pull_event(wait=True)
            if resp != None:
                for val in resp.values():
                    if val == "SHUTDOWN" or val == "RESET":
                        if "guest-reset" in json.dumps(resp["data"]):
                            print("VM is rebooting")
                            print("Reason: guest reset request")
                            cmdCommand = "reboot"
                            time.sleep(3)
                            process = subprocess.Popen(cmdCommand.split(), stdout=subprocess.PIPE)
                            break
                        elif "host-qmp-system-reset" in json.dumps(resp["data"]):
                            print("VM is rebooting")
                            print("Reason: Reboot triggered by host")
                            cmdCommand = "reboot"
                            time.sleep(3)
                            process = subprocess.Popen(cmdCommand.split(), stdout=subprocess.PIPE)
                            break
                        elif "host-qmp-quit" in json.dumps(resp["data"]):
                            print("VM is getting Shutdown")
                            print("Reason: this is in reaction to qmp quit command by host")
                        elif "host-signal" in json.dumps(resp["data"]):
                            print("VM is getting Shutdown")
                            print("Reason: this is in reaction to a signal, such as SIGINT")
                        elif "guest-shutdown" in json.dumps(resp["data"]):
                            print("VM is getting Shutdown")
                            print("Reason: guest Shutdown request, via ACPI or other hardware specific means")
                        elif "guest-panic" in json.dumps(resp["data"]):
                            print("VM is getting Shutdown")
                            print("Reason: guest panic results in to shutdown")
                        elif "host-error" in json.dumps(resp["data"]):
                            print("VM is getting Shutdown")
                            print("Reason: An error prevents further use of guest and results in shutdown")
                        cmdCommand = "shutdown -h now"
                        time.sleep(3)
                        process = subprocess.Popen(cmdCommand.split(), stdout=subprocess.PIPE)
                    elif val == "SUSPEND":
                        # Put the host in to sleep state
                        cmdCommand = "systemctl suspend"
                        process = subprocess.Popen(cmdCommand.split(), stdout=subprocess.PIPE)
                        time.sleep(1)
                        # Send power button event to wake the android
                        cmdCommand = "./scripts/sendkey --vm 0 --power 0"
                        process = subprocess.Popen(cmdCommand.split(), stdout=subprocess.PIPE)

        except KeyboardInterrupt:
            print('interrupted!')
            break

if __name__ == '__main__':
    main()
