#!/bin/bash
#
# Copyright (C) 2020-2022 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# These 2 files should be provided by particular sample:
#  - /etc/demo.env contains environment variables needed to run a demo
#  - demo-setup contains container runtime setup steps
source /etc/demo.env

IGNORE_ERRORS=${IGNORE_ERRORS:-no}

if ! demo-setup; then
  if [[ "${IGNORE_ERRORS}" = "no" ]]; then
    echo "error: failed to setup demo" >&2
    exit -1
  else
    echo "warning: demo setup failed which means that demo won't run properly" >&2
    echo "warning: however you can look inside the container, check package versions" >&2
  fi
fi

if ! test -w $(pwd) && test -w /tmp; then
  echo "info: no write permissions to $(pwd) for current user (UID=$(id -u))" >&2
  echo "info:   changing to /tmp..." >&2
  cd /tmp
fi

"$@"
