# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/boot-arch/android_ia/startup.nsh
##############################################################
installer --batch installer.cmd
# ------------------ END MIX-IN DEFINITIONS ------------------
